version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 8883:8883
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/logs
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped
  lighttpd:
    image: sebp/lighttpd
    volumes:
      - ./website:/var/www/localhost/htdocs
    ports:
      - 8000:80
    tty: true

volumes:
  mosquitto-data:
  mosquitto-logs:
